// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/grpc/server.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OneseismicClient is the client API for Oneseismic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OneseismicClient interface {
	GetFence(ctx context.Context, in *FenceRequest, opts ...grpc.CallOption) (*FenceResponse, error)
}

type oneseismicClient struct {
	cc grpc.ClientConnInterface
}

func NewOneseismicClient(cc grpc.ClientConnInterface) OneseismicClient {
	return &oneseismicClient{cc}
}

func (c *oneseismicClient) GetFence(ctx context.Context, in *FenceRequest, opts ...grpc.CallOption) (*FenceResponse, error) {
	out := new(FenceResponse)
	err := c.cc.Invoke(ctx, "/oneseismic.Oneseismic/GetFence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OneseismicServer is the server API for Oneseismic service.
// All implementations must embed UnimplementedOneseismicServer
// for forward compatibility
type OneseismicServer interface {
	GetFence(context.Context, *FenceRequest) (*FenceResponse, error)
	mustEmbedUnimplementedOneseismicServer()
}

// UnimplementedOneseismicServer must be embedded to have forward compatible implementations.
type UnimplementedOneseismicServer struct {
}

func (UnimplementedOneseismicServer) GetFence(context.Context, *FenceRequest) (*FenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFence not implemented")
}
func (UnimplementedOneseismicServer) mustEmbedUnimplementedOneseismicServer() {}

// UnsafeOneseismicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OneseismicServer will
// result in compilation errors.
type UnsafeOneseismicServer interface {
	mustEmbedUnimplementedOneseismicServer()
}

func RegisterOneseismicServer(s grpc.ServiceRegistrar, srv OneseismicServer) {
	s.RegisterService(&Oneseismic_ServiceDesc, srv)
}

func _Oneseismic_GetFence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OneseismicServer).GetFence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oneseismic.Oneseismic/GetFence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OneseismicServer).GetFence(ctx, req.(*FenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Oneseismic_ServiceDesc is the grpc.ServiceDesc for Oneseismic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Oneseismic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oneseismic.Oneseismic",
	HandlerType: (*OneseismicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFence",
			Handler:    _Oneseismic_GetFence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/server.proto",
}
