name: Performance tests (fast)
# Run jobs that send next request immediately after previous returns

on: workflow_dispatch

jobs:
  prepare_env:
    name: Prepare build environment for Performance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        uses: "./.github/actions/build_performance_tests_image"

  performance_tests:
    # Required secrets:
    #
    # ENDPOINT : URL where server is running
    # STORAGE_ACCOUNT_NAME : name of the storage where server is assigned to (without blob.core.windows.net)
    # STORAGE_ACCOUNT_KEY : key used to access storage
    name: Fast test
    needs: prepare_env

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: Random time slices
            filepath: "/tests/performance/script-random-slice.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
            scenario: "randomSampleSlice"
          - name: Random inline slices
            filepath: "/tests/performance/script-random-slice.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
          - name: Sequential inline slices
            filepath: "/tests/performance/script-sequential-inlineslice.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
          - name: Constant fence
            filepath: "/tests/performance/script-constant-fence.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
          - name: Flat horizon
            filepath: "/tests/performance/script-flat-horizon.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
          - name: Flat horizon, resampling
            filepath: "/tests/performance/script-flat-horizon.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
            scenario: "flatHorizonTenthStepsize"

          # Multi-replica tests

          - name: Several parallel random slice requests to same VDS
            filepath: "/tests/performance/script-various-requests.js"
            vds: "testdata/varsize/varsize_1500_600_2400"

    uses: ./.github/workflows/template_performance.yaml
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      filepath: ${{ matrix.filepath }}
      vds: ${{ matrix.vds }}
      scenario: ${{ matrix.scenario }}
