name: Performance tests (slow)
# Run jobs that wait significant time between receiving response and sending next request

on: workflow_dispatch

jobs:
  prepare_env:
    name: Prepare build environment for Performance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        uses: "./.github/actions/build_performance_tests_image"

  performance_tests_wait:
    # Required secrets:
    #
    # ENDPOINT : URL where server is running
    # STORAGE_ACCOUNT_NAME : name of the storage where server is assigned to (without blob.core.windows.net)
    # STORAGE_ACCOUNT_KEY : key used to access storage
    name: Test with waiting
    needs: prepare_env

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: Random inline slice, 2200_1500_1700
            filepath: "/tests/performance/script-random-slice.js"
            vds: "testdata/varsize/varsize_2200_1500_1700"
            script_duration: "15m"
            iteration_sleep_seconds: 150
          - name: Random xline slice, 2200_1500_1700
            filepath: "/tests/performance/script-random-slice.js"
            vds: "testdata/varsize/varsize_2200_1500_1700"
            script_duration: "15m"
            iteration_sleep_seconds: 150
            scenario: "randomXlineSlice"
          - name: Constant sequential fence, 2200_1500_1700
            filepath: "/tests/performance/script-constant-fence.js"
            vds: "testdata/varsize/varsize_2200_1500_1700"
            script_duration: "15m"
            iteration_sleep_seconds: 150
          - name: Flat horizon, 1500_600_2400
            filepath: "/tests/performance/script-flat-horizon.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
            script_duration: "15m"
            iteration_sleep_seconds: 150
          - name: Flat horizon, 1500_600_2400, resampling
            filepath: "/tests/performance/script-flat-horizon.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
            script_duration: "15m"
            iteration_sleep_seconds: 150
            scenario: "flatHorizonTenthStepsize"
          - name: Curved horizon, 1500_600_2400
            filepath: "/tests/performance/script-curved-horizon.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
            script_duration: "15m"
            iteration_sleep_seconds: 150
          - name: Curved horizon, 1500_600_2400, resampling
            filepath: "/tests/performance/script-curved-horizon.js"
            vds: "testdata/varsize/varsize_1500_600_2400"
            script_duration: "15m"
            iteration_sleep_seconds: 150
            scenario: "curvedHorizonTenthStepsize"

    uses: ./.github/workflows/template_performance.yaml
    secrets: inherit
    with:
      name: ${{ matrix.name }}
      filepath: ${{ matrix.filepath }}
      vds: ${{ matrix.vds }}
      script_duration: ${{ matrix.script_duration }}
      iteration_sleep_seconds: ${{ matrix.iteration_sleep_seconds }}
      scenario: ${{ matrix.scenario }}
